### PR TITLE
Fix RSpec suite and add Travis CI configuration

### PR DESCRIPTION
**Pull request by sgerrand**
:information_desk_person: These changes are twofold:
- ensure that the existing test suite will run ( :smile_cat: ) and support the latest version of RSpec; and
- configure the project so that it can run on Travis CI.

### CODE REVIEW

**Comment by sgerrand** [comment]
:memo: Note that this project will also need to be added to [Travis CI](https://travis-ci.org/realestate-com-au/cfn2dsl). :smile_cat:

**Comment by sgerrand** [comment]
Passing build on Travis: https://travis-ci.org/sgerrand/cfn2dsl/builds/47895039

**Comment by allinwonder** [comment]
Awesome PR !! Big Thanks :beers:

**Comment by sgerrand** [comment]
:bow:

**Pull request merged**
